name: CryptoTick Continuous Deployment

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build All Services
        run: |
          mvn -f services/ingestion-service/pom.xml clean package -DskipTests
          mvn -f services/analytics-service/pom.xml clean package -DskipTests
          mvn -f services/api-service/pom.xml clean package -DskipTests

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::007400345180:role/GitHubActionsWorkflowRole
          aws-region: eu-central-1

      - name: CDK Deploy
        working-directory: infra
        run: |
          cdk deploy --require-approval never --outputs-file outputs.json

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://cryptotick-frontend-007400345180 --delete

      - name: CloudFront Invalidation
        run: |
          DIST_ID=$(jq -r '.InfraStack.DistributionId' infra/outputs.json)
          
          if [ "$DIST_ID" == "null" ] || [ -z "$DIST_ID" ]; then
            echo "Error: DistributionId not found in infra/outputs.json"
            cat infra/outputs.json
            exit 1
          fi
          
          echo "Invalidating Distribution: $DIST_ID"
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"